export const JOB_KEYWORDS = [
  'React JS',
  'Node JS',
  'Nest JS',
  'Next JS',
  'Full Stack Developer',
  'MERN Stack Developer',
  'ME*N Stack Developer',
  'JavaScript Developer',
  'TypeScript Developer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'API Developer',
  'Web Developer',
  'React Developer',
  'Node.js Developer',
  'NestJS Developer',
  'Next.js Developer',
  'Full Stack JavaScript Developer',
  'Full Stack TypeScript Developer',
  'React Node Developer',
  'React Node Nest Developer',
  'React Node Next Developer',
  'React NestJS Developer',
  'React NextJS Developer',
  'MERN Stack Developer',
  'ME*N Stack Developer (MERN/MENN/MENT)',
  'Full Stack React Node Developer',
  'Full Stack React NestJS Developer',
  'Full Stack NextJS Node Developer',
  'NodeJS + NestJS Developer',
  'JavaScript Full Stack Developer',
  'TypeScript Full Stack Developer',
  'React + Node.js + NestJS Engineer',
  'Next.js + Node.js + React Developer',
  'TypeScript + NestJS Backend Engineer',
  'Next.js Full Stack Developer',
  'NestJS Backend Engineer',
  'React + Next.js Frontend Engineer',
  'Next.js + React Frontend Developer',
  'Node.js + NestJS Backend Developer',
  'React Node NestJS full stack developer',
  'Next.js SSR developer',
  'Node.js API developer with NestJS',
  'Frontend React Next.js TypeScript',
  'Backend Node NestJS TypeScript',
  'Remote React Node Nest Next developer',
  'React developer familiar with NestJS',
  'NestJS developer with GraphQL experience',
  'Next.js Tailwind React developer',
];

export const SEARCH_PARAMS = {
  location: 'United States',
  dateSincePosted: '24hr',
  jobType: 'full time',
  remoteFilter: 'remote',
  experienceLevel: 'senior',
  sortBy: 'recent',
};
