[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = [
  "python3.11 -m venv venv",
  ". venv/bin/activate",
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[phases.start]
cmd = "venv/bin/python main.py"
