[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[phases.start]
cmd = "python main.py"
