[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.build]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[phases.start]
cmd = ". venv/bin/activate && python main.py"
